baseURL = 'https://alangsr12.github.io/boue/'
languageCode = 'es'
title = 'BOÜE'
theme = 'hugo-brewm'

[params]
    description = "Mi búnker digital"
    # Aquí iremos agregando lo que necesites del colofón después
    [params.greeter]
    enable = true
    title = "Bienvenido a BOÜE"
    content = "Este es mi búnker digital donde archivo mis proyectos y notas técnicas."
    center = false

    [params.home]
    # Esto activa la sección de los cuadros de categorías
    showCategories = true
    # Cantidad de categorías a mostrar
    numberOfCategories = 4