baseURL = 'https://alangsr12.github.io/boue/'
languageCode = 'es'
title = 'BOÜE'
theme = 'hugo-brewm'

[params]
    description = "Mi búnker digital"

[params.greeter]
    enable = true
    title = "Bienvenido a BOÜE"
    content = "Este es mi búnker digital donde archivo mis proyectos y notas técnicas."
    center = false

[params.home]
    showCategories = true
    numberOfCategories = 4
    # Si querés que los posts se vean en el home, agregá esto:
    showPosts = true