[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 8
        path = 'page'

[es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Español'